hmlr:
  target: dev

  outputs:
    dev:
      type: postgres
      host: postgres
      port: 5432
      user: "{{ env_var('DBT_POSTGRES_USER') }}"
      password: "{{ env_var('DBT_POSTGRES_PASSWORD') }}"
      dbname: warehouse
      schema: analytics
      threads: 4
